# MLflow Configuration
mlflow:
  tracking_uri: "http://127.0.0.1:5000" # MLflow Tracking Server URI
  experiment_name: "flight_delay_prediction"


# Scraper Configuration
scraper:
  base_url: "https://fids.airport.ir/"
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
  airports:
    - name: "فرودگاه مهرآباد"
      url: "/2/اطلاعات-پرواز-فرودگاه-مهرآباد"
    - name: "فرودگاه مشهد"
      url: "/102/اطلاعات-پرواز-فرودگاه-مشهد"
    - name: "فرودگاه شيراز"
      url: "/1/اطلاعات-پرواز-فرودگاه-شيراز"
    - name: "فرودگاه تبريز"
      url: "/103/اطلاعات-پرواز-فرودگاه-تبريز"
    - name: "فرودگاه اصفهان"
      url: "/114/اطلاعات-پرواز-فرودگاه-اصفهان"
    - name: "فرودگاه اهواز"
      url: "/401/اطلاعات-پرواز-فرودگاه-اهواز"
    - name: "فرودگاه بوشهر"
      url: "/104/اطلاعات-پرواز-فرودگاه-بوشهر"
    - name: "فرودگاه بندرعباس"
      url: "/117/اطلاعات-پرواز-فرودگاه-بندرعباس"
    - name: "فرودگاه کرمان"
      url: "/201/اطلاعات-پرواز-فرودگاه-کرمان"
    - name: "فرودگاه ساري"
      url: "/106/اطلاعات-پرواز-فرودگاه-ساري"
    - name: "فرودگاه يزد"
      url: "/107/اطلاعات-پرواز-فرودگاه-يزد"
    - name: "فرودگاه اروميه"
      url: "/110/اطلاعات-پرواز-فرودگاه-اروميه"
    - name: "فرودگاه کرمانشاه"
      url: "/111/اطلاعات-پرواز-فرودگاه-کرمانشاه"
    - name: "فرودگاه رشت"
      url: "/203/اطلاعات-پرواز-فرودگاه-رشت"
    - name: "فرودگاه زاهدان"
      url: "/109/اطلاعات-پرواز-فرودگاه-زاهدان"
    - name: "فرودگاه آبادان"
      url: "/301/اطلاعات-پرواز-فرودگاه-آبادان"
    - name: "فرودگاه گرگان"
      url: "/202/اطلاعات-پرواز-فرودگاه-گرگان"
    - name: "فرودگاه همدان"
      url: "/112/اطلاعات-پرواز-فرودگاه-همدان"
    - name: "فرودگاه اردبيل"
      url: "/113/اطلاعات-پرواز-فرودگاه-اردبيل"
    - name: "فرودگاه ايلام"
      url: "/105/اطلاعات-پرواز-فرودگاه-ايلام"
    - name: "فرودگاه بيرجند"
      url: "/204/اطلاعات-پرواز-فرودگاه-بيرجند"
    - name: "فرودگاه سنندج"
      url: "/402/اطلاعات-پرواز-فرودگاه-سنندج"
    - name: "فرودگاه شهرکرد"
      url: "/108/اطلاعات-پرواز-فرودگاه-شهرکرد"
    - name: "فرودگاه بجنورد"
      url: "/901/اطلاعات-پرواز-فرودگاه-بجنورد"
    - name: "فرودگاه لارستان"
      url: "/601/اطلاعات-پرواز-فرودگاه-لارستان"
    - name: "فرودگاه خرم آباد"
      url: "/701/اطلاعات-پرواز-فرودگاه-خرم-آباد"
    - name: "فرودگاه پارس آبادمغان"
      url: "/702/اطلاعات-پرواز-فرودگاه-پارس-آبادمغان"
    - name: "فرودگاه سمنان"
      url: "/801/اطلاعات-پرواز-فرودگاه-سمنان"
    - name: "فرودگاه شاهرود"
      url: "/802/اطلاعات-پرواز-فرودگاه-شاهرود"
    - name: "فرودگاه نوشهر"
      url: "/1201/اطلاعات-پرواز-فرودگاه-نوشهر"
    - name: "فرودگاه ياسوج"
      url: "/1001/اطلاعات-پرواز-فرودگاه-ياسوج"
    - name: "فرودگاه زنجان"
      url: "/501/اطلاعات-پرواز-فرودگاه-زنجان"
    - name: "فرودگاه اراک"
      url: "/1401/اطلاعات-پرواز-فرودگاه-اراک"
    - name: "فرودگاه زابل"
      url: "/1501/اطلاعات-پرواز-فرودگاه-زابل"
  flight_table_ids:
    input: "Domestic Arrival"
    output: "Domestic Departure"
    internal: "International Arrival"
    external: "International Departure"

# Data Paths (relative to project root)
data_paths:
  raw_data: "data/raw/data.csv"
  cleaned_data: "data/cleaned/cleaned_flight_data.csv"
  processed_data_dir: "data/processed/"
  best_params: "data/processed/best_params.json"

# Association Mining
association_mining:
  min_support: 0.02
  min_threshold: 1
  cleaned:
    path: "data/"
    filename: "cleaned_flight_data.csv"
  results:
    path: "data/mining/results"
    association_rules_filename: "assiciation_rules.csv"

# Machine Learning Pipeline Configurations
pipeline:
  model_registry_name_regression: "flight-delay-regressor"
  model_registry_name_classification: "flight-delay-classifier"
  preprocessor_filename: "preprocessor.joblib"
  model_stage_for_api: "Production"
  test_size: 0.2
  random_state: 42
  delay_threshold_minutes: 15
  model_output_dir: "models/"
  log_file: "logs/pipeline.log"

  # Hyperparameter Tuning Settings
  tuning:
    enabled: true
    n_trials_regression: 50
    n_trials_classification: 25

  # Feature Definitions
  categorical_features:
    - "airline"
    - "destination_or_origin"
    - "aircraft"
    - "airport"
    - "scheduled_day_of_week"
    - "scheduled_season"
    - "scheduled_time_of_day"
    - "is_weekend"
    - "is_Nourooz_4"
    - "is_Nourooz_13"
    - "Normal_holiday"
  numerical_features:
    - "Scheduled_Hour_of_Day"
    - "scheduled_minute"
  target_regression: "delay_minutes"
  target_classification: "is_delayed"

  # Machine Learning Model Parameters (Default values)
  lgbm_params:
    objective: "regression_l1"
    metric: "mae"
    n_estimators: 200
    learning_rate: 0.05
    num_leaves: 31
    verbose: -1
  logistic_params:
    solver: "liblinear"
    C: 1.0
    max_iter: 200