aliases: []
creation_timestamp: 1749230785493
current_stage: None
description: null
last_updated_timestamp: 1749230785493
name: flight-delay-regressor
run_id: ec23e560cdd549f89d89e755a9c3b6bc
run_link: null
source: file:///home/mahan/Projects/Flight_dalay/mlflow_data/120813722374989373/ec23e560cdd549f89d89e755a9c3b6bc/artifacts/lgbm-regressor
status: READY
status_message: null
storage_location: file:///home/mahan/Projects/Flight_dalay/mlflow_data/120813722374989373/ec23e560cdd549f89d89e755a9c3b6bc/artifacts/lgbm-regressor
user_id: null
version: 1
