raw_data_path : "data/final.csv"
cleaned_data_path: "data/cleaned_flight_data.csv"
processed_data_path : "data/processed_data.pkl"
model_output_dir : "models/"
log_file : "logs/pipeline.log"
best_params_path: "config/best_params.json"
#MlFlow
mlflow_experiment_name: "flight_delay_prediction"

# Data processings
test_size : 0.2
random_state : 42
delay_threshold_minutes : 15 # delays more than this would be considered LATE


# Hyperparameter Tuning Settings
tuning:
  enabled: true # Set to false to skip tuning and use default params
  n_trials_regression: 50  # Number of tuning trials for regression
  n_trials_classification: 25 # same as one above

# Features
categorical_features : 
  - "airline"
  - "destination_or_origin"
  - "aircraft"
  - "airport"
  - "scheduled_day_of_week"
  - "scheduled_season"
  - "scheduled_time_of_day"
  - "is_weekend" # Already 0/1 but treating as category is fine for OHE
  - "is_Nourooz_4"
  - "is_Nourooz_13"
  - "Normal_holiday"

numerical_features :
  - "Scheduled_Hour_of_Day"
  - "scheduled_minute"

target_regression: "delay_minutes"
target_classification : "is_delayed"

data: 
  cleaned:
    path: "data/"
    filename: "cleaned_flight_data.csv"
  results:
    path: "data/mining/results"
    association_rules_filename: "assiciation_rules.csv"


association_mining:
  min_support: 0.02
  min_threshold: 1

# Model parameters
lgbm_params:
  objective: "regression_l1" # For MAE
  metric: "mae"
  n_estimators: 200
  learning_rate: 0.05
  num_leaves: 31
  verbose: -1 # Suppress LightGBM output during training
  # Add other LightGBM parameters as needed

logistic_params:
  solver: "liblinear"
  C: 1.0
  max_iter: 200
  # Add other params if needed

